# Generated by Django 3.0.3 on 2020-08-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnist', '0002_auto_20200824_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.AddField(
            model_name='img',
            name='label',
            field=models.TextField(default=''),
        ),
    ]
